# Ridge Regression
> advertising.csv

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import plotly.express as px
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, Ridge

In [2]:
df = pd.read_csv('advertising.csv')
df.head()

      TV  Radio  Newspaper  Sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3   12.0
3  151.5   41.3       58.5   16.5
4  180.8   10.8       58.4   17.9

In [3]:
# features and target
x = df.iloc[:, 0:-1]
y = df.iloc[:, -1]

# train test split
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)

In [4]:
df.corr()

                 TV     Radio  Newspaper     Sales
TV         1.000000  0.054809   0.056648  0.901208
Radio      0.054809  1.000000   0.354104  0.349631
Newspaper  0.056648  0.354104   1.000000  0.157960
Sales      0.901208  0.349631   0.157960  1.000000

In [8]:
# true data
fig = px.scatter_3d(df, 
                    x = df['TV'], 
                    y = df['Radio'], 
                    z = df['Sales'], 
                    color = df['Sales'], 
                    color_continuous_scale='thermal')
fig.show()

## 🔰 Linear Regression

In [9]:
# linear Regression
lr = LinearRegression()
lr.fit(x_train, y_train)
y_Pred = lr.predict(x_test)


print('intercept: ',lr.intercept_)
print('coef: ',lr.coef_)
print('R2 score: ',r2_score(y_test, y_Pred))

intercept:  4.714126402214134
coef:  [0.05450927 0.10094536 0.00433665]
R2 score:  0.9059011844150826

In [20]:
# plane of regression
x_range = np.linspace(df['TV'].min(), df['TV'].max(), 15)
y_range = np.linspace(df['Radio'].min(), df['Radio'].max(), 15)

xx,yy = np.meshgrid(x_range, y_range)
news_mean = df['Newspaper'].mean()
news_col = np.full(xx.ravel().shape, news_mean)

pred_input = np.c_[xx.ravel(), yy.ravel(), news_col]
zz = lr.predict(pred_input).reshape(xx.shape)

fig = px.scatter_3d(df, 
                    x = df['TV'], 
                    y = df['Radio'], 
                    z = df['Sales'], 
                    color = df['Sales'], 
                    color_continuous_scale='thermal')

fig.add_surface(x = x_range, y = y_range, z = zz, colorscale='twilight')
fig.show()

/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2739: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names

## 🚀 Ridge Regression

In [21]:
r = Ridge(alpha = 0.001)
r.fit(x_train, y_train)
y_pred = r.predict(x_test)

print('Intercept: ',r.intercept_)
print('Coef: ',r.coef_)
print('R2 Score: ',r2_score(y_test, y_pred))

Intercept:  4.714126455669611
Coef:  [0.05450927 0.10094536 0.00433665]
R2 Score:  0.905901183146641

In [24]:
x_range = np.linspace(df['TV'].min(), df['TV'].max(), 15)
y_range = np.linspace(df['Radio'].min(), df['Radio'].max(), 15)

xx,yy = np.meshgrid(x_range, y_range)
news_mean = df['Newspaper'].mean()
news_col = np.full(xx.ravel().shape, news_mean)

pred_input = np.c_[xx.ravel(), yy.ravel(), news_col]
zz = r.predict(pred_input).reshape(xx.shape)

fig = px.scatter_3d(df, x = df['TV'],
                    y = df['Radio'],
                    z = df['Sales'],
                    color=df['Sales'],
                    color_continuous_scale='twilight',
                    title='True data')
fig.add_surface(x = x_range, y = y_range, z = zz, colorscale='magma')

fig.show()

/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2739: UserWarning:

X does not have valid feature names, but Ridge was fitted with feature names

## 👾 User input output prediction

In [25]:
# take user input
tv = float(input('TV budget: '))
radio = float(input('Radio Budget: '))
newspaper = float(input('Newspaper Budget: '))

# input array
user_ip = np.array([[tv, radio, newspaper]])

# Linear Regression input
lr_prediction = lr.predict(user_ip)[0]

# Ridge Regression input
r_prediction = r.predict(user_ip)[0]

print('✅ PREDICTIONS...\n')
print('Linear Regression prediction: ',lr_prediction)
print('Ridge Regression prediction: ',r_prediction)

✅ PREDICTIONS...

Linear Regression prediction:  10.554683752304475
Ridge Regression prediction:  10.554683721584839

/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2739: UserWarning:

X does not have valid feature names, but LinearRegression was fitted with feature names

/Users/lucifer/Library/Python/3.9/lib/python/site-packages/sklearn/utils/validation.py:2739: UserWarning:

X does not have valid feature names, but Ridge was fitted with feature names